### ISSUE TITLE
OpenGraph data storage

### ISSUE THREAD

**Issue by ideag** [ideag/content-cards#6]
Better OpenGraph data storage.

To Do:
- [x] store OG data in `postmeta`
- [x] update OG data via `WP_Cron`
- [x] add an option to Plugin Settings UI for update interval.  
- [x] cleanup `postmeta` fields if link gets removed from post
- [x] ? add a cool down interval before retrying to get initial OG data if first attempt was unsuccessful

---

Ideas:

> Optional expiration time for the opengraph oembeds and refresh them in the background. (Maybe possible to piggyback on core WP functions.) _via @khromov_
> 
>  save the og data as a custom field into postmeta. That way it minimizes delays due to link rot and page load times waiting for embeds. _via @lincourtl_

**Comment by ideag** [comment]
I am leaning towards storing OpenGraph data in postmeta fields and updating them via wp_cron, rather than transients.
The reasoning is as follows - transients are _temporary_ by nature, and when the transient expires, WP has to call the remote link again. And that would probably happen during an ordinary page view call, thus impacting page load time for ordinary visitor.
Postmeta, on the other hand, is _persistent_, so even if the original link goes away (link rot), the original OG data would still be available and we could still display a nice card for the link. And updates to the OG data could be done via wp_cron, without impacting page load times. 
I think it would probably be advisable to cache the image from the remote server locally, too. Though in this case we should also figure out how to cleanup, when/if image is no longer needed (the image changed, or the link was removed from the post, etc.), or they could pile up over time.

**Comment by khromov** [comment]
Excellent ideas @ideag , fully agree with storing in postmeta and updating via wp corn.

On the one hand it would be nice to import the OG image into the media library so that image sizes are generated. That way the cards could use any image size registered in WP. We'd probably need to find some way to "hide" these from the media library so they don't cause clutter.

On the other hand, if we don't import the OG image we'll have a much cleaner solution. Basically the wp_cron (that can be run daily) wiil figure out if the OG image has been removed and then simply remove it so it won't show up in the future.

The only problem would be if the OG image 404:s randomly during the day, we will have to wait for wp cron to remove it. In my experience, this happens very rarely.

Both are good options but for ease of implementation i would vote for the second alternative. What do you think @ideag ?

**Comment by ideag** [comment]
I am also leaning towards the second option, at least for v1. But I think (optional) caching to the media library could be added further down the roadmap. I like that option as it would give us a chance to use unified dimensions for images, because as I see now, size of open graph images differs quite a lot between different sites.
